dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin

addons:
  apt:
    sources:
      - avsm

env:
  global:
    - NJOBS=2
    - COMPILER="4.08.0"
    - CAMLP5_VER="7.06"
    - FINDLIB_VER="1.8.0"
    - NATIVE_COMP="yes"
    - COQ_VER="8.10+beta2"
    - OPAMVERBOSE=3

install:
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
  - export PATH=$HOME/bin:$PATH
  - which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
  - opam --version
  - opam update
  - eval $(opam config env)
  - opam config list
  - opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || echo "coq-core-dev registered"
  - opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind.${FINDLIB_VER} coq.${COQ_VER} dune
  - opam upgrade -y coq.${COQ_VER}
  - opam list
  - |
    git clone https://github.com/ANSSI-FR/coq-prelude ${HOME}/coq-prelude
    cd ${HOME}/coq-prelude
    git checkout refactoring
    dune build
    dune install
    cd -

script:
  - git clone https://git.sr.ht/~lthms/coqbook.css ${HOME}/coqbook.css
  - ./configure.sh
  - make install
  - ./run-tests.sh
  - make html
  - find html -name coqdoc.css -exec cp ${HOME}/coqbook.css/coqdoc.css {} \;

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: html
