dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin

addons:
  apt:
    sources:
      - avsm

env:
  global:
    - NJOBS=2
    - COMPILER="4.06.0"
    - CAMLP5_VER="7.06"
    - FINDLIB_VER="1.8.0"
    - NATIVE_COMP="yes"
    - COQ_VER="8.9.0"
    - OPAMVERBOSE=3

install:
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
  - export PATH=$HOME/bin:$PATH
  - which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
  - opam --version
  - opam update
  - eval $(opam config env)
  - opam config list
  - opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || echo "coq-core-dev registered"
  - opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind.${FINDLIB_VER} coq.${COQ_VER}
  - opam upgrade -y coq.${COQ_VER}
  - opam list
  - git clone https://github.com/ANSSI-FR/coq-prelude ${HOME}/coq-prelude; cd ${HOME}/coq-prelude; ./configure.sh; make ; make install; cd -

script:
  - ./configure.sh
  - make install
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: html
